- hosts: naszaaplikacja


  tasks:
  - name: write that the weather is good
    shell: echo 'weather is good'
    register: yourvar

  - name: confirmed
    shell: echo 'yes it is ok'
    when:
      - '"is good" in yourvar.stdout'
    changed_when:
      - '"good" not in yourvar.stdout'

  - name: print current time/date
    debug:
      msg: "{{ lookup('pipe', 'date') }}, {{ lookup('pipe', 'whoami') }}"

  - name: curl http://mgmt2.muszynski.pro:5888
    debug:
      msg: "{{ lookup('url', 'http://mgmt2.muszynski.pro:5888') }}"
    register: curlresult

  - name: print curlresult
    debug:
      msg: "{{ curlresult }}"

  - name: assert current status
    assert:
      that:
        - '"szkolenieOK" in curlresult.msg'
        - '"is good" in yourvar.stdout'

  - command: /usr/bin/false
    retries: 3
    delay: 3
    register: result
    until: result.rc == 0
    #ignore_errors: yes
    #failed_when: false
