- hosts: our_app

  become: true

  #variables usefull for templating apache and app
  vars:
    web_dir: /var/www/szkolenie.pl
    app_dir: "{{ web_dir }}/aplikacja"
    log_dir: "{{ web_dir }}/logs"
    port: 5081

  pre_tasks: []

#  tasks:
#    - name: 'install apache2, libapache2-mod-wsgi'
#
#    - name: 'install apache2, libapache2-mod-wsgi python-dev with LOOP'
#
#    - git:
#
#    - name: 'initialize venv and install dependencies'
#
#    - name: 'deploy virtualhost our_app.apache.conf as a template'
#
#    - name: 'deploy our_app.wsgi as a template'
#
#    - name: 'wlacz virtualhost'
#
#    - name: 'configure apache to listen on proper port'
#  
#    - name: 'deploy config.cfg as a template'
#
#    - name: 'create log dir'
#
#    - name: 'restart apache'
