####
#port 5082 ports.conf apache

    - name: 'install apache2, libapache2-mod-wsgi'
      apt: 
        pkg:
          - apache2
          - libapache2-mod-wsgi-py3 #python3
      tags:
        - first_tag

    - name: 'install apache2, libapache2-mod-wsgi python-dev with LOOP'
      apt: 
        name: "{{ item }}"
      loop:
        - apache2
        - libapache2-mod-wsgi-py3 #python3
        - python3-dev

    - git:
        repo: https://github.com/sirkubax/flask-app.git
        dest: "{{ web_dir }}"
        force: yes
      name: 'clone git repo'

    - pip: 
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ app_dir }}/venv"
      name: 'initialize venv and install dependencies'

    - name: 'deploy virtualhost our_app.apache.conf as a template'
      template:
          src: our_app.apache.conf
          dest: /etc/apache2/sites-available/
          backup: True

    - name: 'deploy our_app.wsgi as a template'
      template:
          src: our_app.wsgi
          dest: "{{ app_dir }}"
          backup: True

    - name: 'wlacz virtualhost'
      shell: a2ensite {{ item }}
      args:
        creates: /etc/apache2/sites-enabled/{{ item }}
      loop: 
        - our_app.apache.conf

    - name: 'configure apache to listen on proper port'
      lineinfile: 
        dest: /etc/apache2/ports.conf
        line: "Listen {{ port }}"
        regexp: "^Listen {{ port }}"
  
    - name: 'deploy config.cfg as a template'
      template:
        src: config.cfg.example
        dest: "{{ app_dir }}/config.cfg"
        backup: True

    - name: 'create log dir'
      file:
        state: directory
        path: "{{ log_dir }}"
        owner: www-data
        group: www-data
        mode: 0755

    - name: 'restart apache'
      service:
        name: apache2
        state: restarted

