- hosts: apache

  tasks:
  - name: Install packages
    apt: name={{ item }}
    with_items:
      - apache2
    notify:
      - Wait for instances to listen on port 80
    become: True

  handlers:
  - name: Wait for instances to listen on port 80
    wait_for: 
      state: started 
      host: localhost 
      port: 80 
      timeout: 15 
      delay: 5

