---
- hosts: apache

  tasks:
  - name: update cache 
    apt: 
      update_cache: yes 
      cache_valid_time: 7200
    changed_when: False
    become: True

  - name: install packages
    apt: 
      pkg:
        - apache2
        - htop
        #here define next item - dstat
    become: True

  - name: Wait for instances to listen on port 80
    wait_for: state=started host=localhost port=80 timeout=15 delay=5

#  - name: create file 
#    #use proper module to create file
#
#  - name: create file /tmp/usernameXX with a content OK
#    #possible modules: shell, template, copy
