---
- hosts: apache

  vars:
      vars_files_var: ["vars/training.yml", "vars/training_vault.yml"]

  pre_tasks:
      - include_vars: "{{ item }}"
        with_items: "{{ vars_files_var }}"

  tasks:
    - name: "debug file module"
      ping:

