---
- hosts: apache

  vars:
      vars_files_var: ["vars/training.yml", "vars/training_vault.yml"]

  pre_tasks:
      - include_vars: "{{ item }}"
        with_items: "{{ vars_files_var }}"

  tasks:
    - name: "show time"
      shell: date

  #please examin output of known facts from sys_debug (look for ansible_ipv4)

  roles:
    - sys_debug
    - { role: app_apache_template }

